In [1]:
import numpy as np
from tabulate import tabulate
import pandas as pd

##### <font color='red'>Задание</font>

Создать класс, реализующий функционал учета рейтинга студентов **StudentsRaiting**. Класс должен иметь конструктор, который будет принимать список студентов с результатами сданных экзаменов, реализованый в виде словаря с ключем "ФИО студента" и оценками по экзаменам по 4 предметам (Программирование, Дискретная математика, Иностранный язык, Философия), представленными в виде упорядоченного множества (кортежа). Например:

`{"Иванов Петр Николавич":(3,3,5,4), "Петров Иван Константинович":(5,4,5,4)}`

Релизовать методы: 
- добавления студента с оценками по экзаменам
- удаления студента из рейтинга 
- получения списка студентов с рейтингом выше порогового
- метод демонстрации работы методов класса с выводом результатов на печать в виде текстовой таблицы.

Примечание:
Рейтинг составляется по суммарному баллу по всем предметам.

In [2]:
class StudentsRaiting:

    # Constructor
    def __init__(self, students):
        self.students = students  
 

    def printTable(self, data = None):
        if data == None: 
            data = self.students
        df = pd.DataFrame({'Student' : list(data.keys()),
                       'Marks' : list(data.values())})
        print(tabulate(df, headers='keys', tablefmt='psql'))
   
    def show(self):
        print(self.students)
        
    def addStud(self,student):
        if type(student) is dict:
            self.students.update(student)
        
    def delStud(self,student):
        self.students.pop(student,None)
        
    def getStudsWithRating(self,rating):
        if type(rating) is not int: 
            return None
        result = {}
        for a,b in self.students.items():
            if sum(b)>=rating:
                result.update({a:b})
        self.printTable(result)
        
       

print("Initializing new journal:")

journal = StudentsRaiting({"Иванов Петр Николавич":(3,3,5,4),
                     "Петров Иван Константинович":(5,4,5,4),
                     "Иванов Иван Константинович":(4,5,3,5),
                     "Петров Петр Николавич":(4,4,3,4)})  

journal.printTable() 



print("\n\n\n")

print("Adding new students:")

journal.addStud({"Аааа ААА Аааааа":(5,5,5,5),
                 "BBB bbb BBBBbbbb":(2,3,2,2)})

journal.printTable() 



print("\n\n\n")

print("Removing student by name:")

journal.delStud("Аааа ААА Аааааа")

journal.printTable() 


print("\n\n\n")

print("Getting students with good rating (more than 15):")

journal.getStudsWithRating(15)








Initializing new journal:
+----+----------------------------+--------------+
|    | Student                    | Marks        |
|----+----------------------------+--------------|
|  0 | Иванов Петр Николавич      | (3, 3, 5, 4) |
|  1 | Петров Иван Константинович | (5, 4, 5, 4) |
|  2 | Иванов Иван Константинович | (4, 5, 3, 5) |
|  3 | Петров Петр Николавич      | (4, 4, 3, 4) |
+----+----------------------------+--------------+




Adding new students:
+----+----------------------------+--------------+
|    | Student                    | Marks        |
|----+----------------------------+--------------|
|  0 | Иванов Петр Николавич      | (3, 3, 5, 4) |
|  1 | Петров Иван Константинович | (5, 4, 5, 4) |
|  2 | Иванов Иван Константинович | (4, 5, 3, 5) |
|  3 | Петров Петр Николавич      | (4, 4, 3, 4) |
|  4 | Аааа ААА Аааааа            | (5, 5, 5, 5) |
|  5 | BBB bbb BBBBbbbb           | (2, 3, 2, 2) |
+----+----------------------------+--------------+




Removing student by name:
+

##### <font color=red>Задание</font>
Создать массив значений типа `int32` размером 10х10, состоящий из равномерно распределенных случайных чисел от 0 до 100. Получить 4 копии этого массива со значениями типа `uint32`,`int64`,`uint64`,`float`. Для каждого массива вывести сведения: число размерностей, форма, размер, тип данных, размер каждого значения в байтах и размер всего массива в байтах.


In [3]:
massives = ([np.random.randint(100, size=(10, 10))])

massives.extend([np.array(massives[0], dtype=np.uint32),
             np.array(massives[0], dtype=np.int64),
             np.array(massives[0], dtype=np.uint64),
             np.array(massives[0], dtype=np.float)])

df = pd.DataFrame({'Name' : ["Main","Copy №1","Copy №2","Copy №3","Copy №4",],
                   'Type' : list(map(lambda s: s.dtype, massives)),
                   'Dimensions' : list(map(lambda s: s.ndim, massives)),
                   'Shape' : list(map(lambda s: s.shape, massives)),
                   'Size' : list(map(lambda s: s.size, massives)),
                   'ItemWeight(Bytes)' : list(map(lambda s: s.itemsize, massives)),
                   'Weight(Bytes)' : list(map(lambda s: s.nbytes, massives))})
print(tabulate(df, headers='keys', tablefmt='psql'))

+----+---------+---------+--------------+----------+--------+---------------------+-----------------+
|    | Name    | Type    |   Dimensions | Shape    |   Size |   ItemWeight(Bytes) |   Weight(Bytes) |
|----+---------+---------+--------------+----------+--------+---------------------+-----------------|
|  0 | Main    | int32   |            2 | (10, 10) |    100 |                   4 |             400 |
|  1 | Copy №1 | uint32  |            2 | (10, 10) |    100 |                   4 |             400 |
|  2 | Copy №2 | int64   |            2 | (10, 10) |    100 |                   8 |             800 |
|  3 | Copy №3 | uint64  |            2 | (10, 10) |    100 |                   8 |             800 |
|  4 | Copy №4 | float64 |            2 | (10, 10) |    100 |                   8 |             800 |
+----+---------+---------+--------------+----------+--------+---------------------+-----------------+


##### <font color=red>Задание</font>
Выполнить следующий код и объяснить результат.

In [6]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("A mass:", a)
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print("col_r1, col_r1.shape: \n", col_r1, col_r1.shape)
print()
print("col_r2, col_r2.shape: \n",col_r2, col_r2.shape)

A mass: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
col_r1, col_r1.shape: 
 [ 2  6 10] (3,)

col_r2, col_r2.shape: 
 [[ 2]
 [ 6]
 [10]] (3, 1)


##### <font color=green>Ответ</font>
col_r1 = a[:, 1] - берем второй элемент из всех строк исходного массива. ":" - выбрать все элементы данного измерения массива

col_r2 = a[:, 1:2] - берем С первого ПО второй элемент из всех строк исходного массива.

Функция Shape позволяет узнать форму массива.

##### <font color=red>Задание</font>
Создать массив случайных целочисленных значений (от -100 до 100) размером 8x8. Используя индексацию булевыми массивами получить:
1. Все элементы, значения которых являются четными числами. Вывести их маску в массиве.
2. Все элементы, значения которых попадают в диапазон от 10 до 50. Вывести их маску в массиве.
3. Все элементы, значения которых являются четными числами и попадают в диапазон от 10 до 50. Вывести их маску в массиве.
4. Все элементы, значения которых являются нечетными числами и модуль значения которых из диапазона от 10 до 50. Вывести их маску в массиве.
5. Все элементы, значения которых являются нечетными числами или отрицательными.