In [1]:
import numpy as np
from tabulate import tabulate
import pandas as pd

##### <font color='red'>Задание</font>

Создать класс, реализующий функционал учета рейтинга студентов **StudentsRaiting**. Класс должен иметь конструктор, который будет принимать список студентов с результатами сданных экзаменов, реализованый в виде словаря с ключем "ФИО студента" и оценками по экзаменам по 4 предметам (Программирование, Дискретная математика, Иностранный язык, Философия), представленными в виде упорядоченного множества (кортежа). Например:

`{"Иванов Петр Николавич":(3,3,5,4), "Петров Иван Константинович":(5,4,5,4)}`

Релизовать методы: 
- добавления студента с оценками по экзаменам
- удаления студента из рейтинга 
- получения списка студентов с рейтингом выше порогового
- метод демонстрации работы методов класса с выводом результатов на печать в виде текстовой таблицы.

Примечание:
Рейтинг составляется по суммарному баллу по всем предметам.

In [2]:
class StudentsRaiting:

    # Constructor
    def __init__(self, students):
        self.students = students  
 

    def printTable(self, data = None):
        if data == None: 
            data = self.students
        df = pd.DataFrame({'Student' : list(data.keys()),
                       'Marks' : list(data.values())})
        print(tabulate(df, headers='keys', tablefmt='psql'))
   
    def show(self):
        print(self.students)
        
    def addStud(self,student):
        if type(student) is dict:
            self.students.update(student)
        
    def delStud(self,student):
        self.students.pop(student,None)
        
    def getStudsWithRating(self,rating):
        if type(rating) is not int: 
            return None
        result = {}
        for a,b in self.students.items():
            if sum(b)>=rating:
                result.update({a:b})
        self.printTable(result)
        
       

print("Initializing new journal:")

journal = StudentsRaiting({"Иванов Петр Николавич":(3,3,5,4),
                     "Петров Иван Константинович":(5,4,5,4),
                     "Иванов Иван Константинович":(4,5,3,5),
                     "Петров Петр Николавич":(4,4,3,4)})  

journal.printTable() 



print("\n\n\n")

print("Adding new students:")

journal.addStud({"Аааа ААА Аааааа":(5,5,5,5),
                 "BBB bbb BBBBbbbb":(2,3,2,2)})

journal.printTable() 



print("\n\n\n")

print("Removing student by name:")

journal.delStud("Аааа ААА Аааааа")

journal.printTable() 


print("\n\n\n")

print("Getting students with good rating (more than 15):")

journal.getStudsWithRating(15)








Initializing new journal:
+----+----------------------------+--------------+
|    | Student                    | Marks        |
|----+----------------------------+--------------|
|  0 | Иванов Петр Николавич      | (3, 3, 5, 4) |
|  1 | Петров Иван Константинович | (5, 4, 5, 4) |
|  2 | Иванов Иван Константинович | (4, 5, 3, 5) |
|  3 | Петров Петр Николавич      | (4, 4, 3, 4) |
+----+----------------------------+--------------+




Adding new students:
+----+----------------------------+--------------+
|    | Student                    | Marks        |
|----+----------------------------+--------------|
|  0 | Иванов Петр Николавич      | (3, 3, 5, 4) |
|  1 | Петров Иван Константинович | (5, 4, 5, 4) |
|  2 | Иванов Иван Константинович | (4, 5, 3, 5) |
|  3 | Петров Петр Николавич      | (4, 4, 3, 4) |
|  4 | Аааа ААА Аааааа            | (5, 5, 5, 5) |
|  5 | BBB bbb BBBBbbbb           | (2, 3, 2, 2) |
+----+----------------------------+--------------+




Removing student by name:
+

##### <font color=red>Задание</font>
Создать массив значений типа `int32` размером 10х10, состоящий из равномерно распределенных случайных чисел от 0 до 100. Получить 4 копии этого массива со значениями типа `uint32`,`int64`,`uint64`,`float`. Для каждого массива вывести сведения: число размерностей, форма, размер, тип данных, размер каждого значения в байтах и размер всего массива в байтах.


In [3]:
massives = ([np.random.randint(100, size=(10, 10))])

massives.extend([np.array(massives[0], dtype=np.uint32),
             np.array(massives[0], dtype=np.int64),
             np.array(massives[0], dtype=np.uint64),
             np.array(massives[0], dtype=np.float)])

df = pd.DataFrame({'Name' : ["Main","Copy №1","Copy №2","Copy №3","Copy №4",],
                   'Type' : list(map(lambda s: s.dtype, massives)),
                   'Dimensions' : list(map(lambda s: s.ndim, massives)),
                   'Shape' : list(map(lambda s: s.shape, massives)),
                   'Size' : list(map(lambda s: s.size, massives)),
                   'ItemWeight(Bytes)' : list(map(lambda s: s.itemsize, massives)),
                   'Weight(Bytes)' : list(map(lambda s: s.nbytes, massives))})
print(tabulate(df, headers='keys', tablefmt='psql'))

+----+---------+---------+--------------+----------+--------+---------------------+-----------------+
|    | Name    | Type    |   Dimensions | Shape    |   Size |   ItemWeight(Bytes) |   Weight(Bytes) |
|----+---------+---------+--------------+----------+--------+---------------------+-----------------|
|  0 | Main    | int32   |            2 | (10, 10) |    100 |                   4 |             400 |
|  1 | Copy №1 | uint32  |            2 | (10, 10) |    100 |                   4 |             400 |
|  2 | Copy №2 | int64   |            2 | (10, 10) |    100 |                   8 |             800 |
|  3 | Copy №3 | uint64  |            2 | (10, 10) |    100 |                   8 |             800 |
|  4 | Copy №4 | float64 |            2 | (10, 10) |    100 |                   8 |             800 |
+----+---------+---------+--------------+----------+--------+---------------------+-----------------+


##### <font color=red>Задание</font>
Выполнить следующий код и объяснить результат.

In [4]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("A mass:", a)
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print("col_r1, col_r1.shape: \n", col_r1, col_r1.shape)
print()
print("col_r2, col_r2.shape: \n",col_r2, col_r2.shape)

A mass: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
col_r1, col_r1.shape: 
 [ 2  6 10] (3,)

col_r2, col_r2.shape: 
 [[ 2]
 [ 6]
 [10]] (3, 1)


##### <font color=green>Ответ</font>
col_r1 = a[:, 1] - берем второй элемент из всех строк исходного массива. ":" - выбрать все элементы данного измерения массива

col_r2 = a[:, 1:2] - берем С первого ПО второй элемент из всех строк исходного массива.

Функция Shape позволяет узнать форму массива.

##### <font color=red>Задание</font>
Создать массив случайных целочисленных значений (от -100 до 100) размером 8x8. Используя индексацию булевыми массивами получить:
1. Все элементы, значения которых являются четными числами. Вывести их маску в массиве.
2. Все элементы, значения которых попадают в диапазон от 10 до 50. Вывести их маску в массиве.
3. Все элементы, значения которых являются четными числами и попадают в диапазон от 10 до 50. Вывести их маску в массиве.
4. Все элементы, значения которых являются нечетными числами и модуль значения которых из диапазона от 10 до 50. Вывести их маску в массиве.
5. Все элементы, значения которых являются нечетными числами или отрицательными.

In [5]:


main_mass = np.random.randint(-100, 100, size=(8, 8))
print('main_mass\n',main_mass)

print("\n\n\nTask №1:\nВсе элементы, значения которых являются четными числами:\n",
      main_mass[main_mass%2==0])
print("\n\nМаска:\n",(main_mass%2==0))


print("\n\n\nTask №2:\nВсе элементы, значения которых попадают в диапазон от 10 до 50:\n",
      main_mass[(main_mass >=10 )&(main_mass <=50 )])
print("\n\nМаска:\n",((main_mass >=10 )&(main_mass <=50 )))

print("\n\n\nTask №3:\nВсе элементы, значения которых являются четными числами и попадают в диапазон от 10 до 50:\n",
      main_mass[(main_mass%2==0)&(main_mass >=10 )&(main_mass <=50 )])
print("\n\nМаска:\n",((main_mass%2==0)&(main_mass >=10 )&(main_mass <=50 )))

print("\n\n\nTask №4:\nВсе элементы, значения которых являются нечетными числами",
      " и модуль значения которых из диапазона от 10 до 50:\n",
      main_mass[(main_mass%2!=0)&(abs(main_mass) >=10 )&(abs(main_mass) <=50 )])
print("\n\nМаска:\n",((main_mass%2!=0)&(abs(main_mass) >=10 )&(abs(main_mass) <=50 )))


print("\n\n\nTask №5:\nВсе элементы, значения которых являются нечетными числами или отрицательными:\n",
      main_mass[(main_mass%2!=0)|(main_mass <0 )])
print("\n\nМаска:\n",((main_mass%2!=0)|(main_mass <0 )))

main_mass
 [[ 90 -17  62  66  98 -63 -42  -4]
 [ 33 -45  -8 -70 -84 -87  26  67]
 [ 15  65  55  -6 -38  61  86  85]
 [ 14 -46  65 -73 -99  13  52  68]
 [ 97  72 -57 -19  86   7  51 -33]
 [ 42  92  18  65 -19 -94 -53  24]
 [ 95 -27  45  -9 -46  46 -66  63]
 [ 29 -89  33  55 -52  98 -51  -8]]



Task №1:
Все элементы, значения которых являются четными числами:
 [ 90  62  66  98 -42  -4  -8 -70 -84  26  -6 -38  86  14 -46  52  68  72
  86  42  92  18 -94  24 -46  46 -66 -52  98  -8]


Маска:
 [[ True False  True  True  True False  True  True]
 [False False  True  True  True False  True False]
 [False False False  True  True False  True False]
 [ True  True False False False False  True  True]
 [False  True False False  True False False False]
 [ True  True  True False False  True False  True]
 [False False False False  True  True  True False]
 [False False False False  True  True False  True]]



Task №2:
Все элементы, значения которых попадают в диапазон от 10 до 50:
 [33 26 15 14 13 42 

##### <font color=red>Задание</font>
Написать функцию, которая из исходного массива размером 8х8 получает (при помощи операций разбиения и объединения) массив, в котором переставлены квадранты 1-й с 3-м, 2-й с 4-м по сравнению с исходным массивом. Продемонстрировать работу функции все шаги алгоритма сопроводить подробными комментариями и отладочным выводом промежуточных результатов.

Т.е. например из массива

`[[49  5 49  1 28 27 31 35]
 [21 12 34  3 20  2 42 48]
 [21 22 39 23 28 31 47 34]
 [37  6 24 22 19 32 27 20]
 [12  0  1 40  2 30 42 47]
 [33 40 10  8 29 48 24  8]
 [14 49  8 46 23 18 10 49]
 [15 20 49 30  9 18 42  5]]`
 
должен получиться массив 

 `[[ 2 30 42 47 12  0  1 40]
 [29 48 24  8 33 40 10  8]
 [23 18 10 49 14 49  8 46]
 [ 9 18 42  5 15 20 49 30]
 [28 27 31 35 49  5 49  1]
 [20  2 42 48 21 12 34  3]
 [28 31 47 34 21 22 39 23]
 [19 32 27 20 37  6 24 22]]`

In [6]:
def replace_squares(mass,mid=False):
    if list(mass.shape)[0]%2!=0 or list(mass.shape)[1]%2!=0:
        return None    
    sh = [list(mass.shape)[0]//2,list(mass.shape)[1]//2]    
    res = mass.copy()
    squares = (mass[:sh[0],:sh[1]],
              mass[sh[0]:,:sh[1]],
              mass[:sh[0],sh[1]:],
              mass[sh[0]:,sh[1]:])
    if mid:
        middle_results = list(squares)
        print("\n\nMiddle results:\n\nFirst square: \n",middle_results[0],
              "\nSecond square: \n",middle_results[1],
              "\nThird square: \n",middle_results[2],
              "\nFourth square: \n",middle_results[3])
    res[sh[0]:,sh[1]:],res[:sh[0],sh[1]:],res[sh[0]:,:sh[1]],res[:sh[0],:sh[1]]=squares
    return res
    
    
#massive = np.random.randint(-5, 5, size=(8,8))
massive = np.array([[49,  5, 49,  1, 28, 27, 31, 35],
                    [21, 12, 34,  3, 20,  2, 42, 48],
                    [21, 22, 39, 23, 28, 31, 47, 34],
                    [37,  6, 24, 22, 19, 32, 27, 20],
                    [12,  0,  1, 40,  2, 30, 42, 47],
                    [33, 40, 10,  8, 29, 48, 24,  8],
                    [14, 49,  8, 46, 23, 18, 10, 49],
                    [15, 20, 49, 30,  9, 18, 42,  5]])
print("Input massive:\n", massive)
#if middle results are in need, add True
#massive = replace_squares(massive,True)
massive = replace_squares(massive)
print("\n\n\nRESULT:\n",massive)

Input massive:
 [[49  5 49  1 28 27 31 35]
 [21 12 34  3 20  2 42 48]
 [21 22 39 23 28 31 47 34]
 [37  6 24 22 19 32 27 20]
 [12  0  1 40  2 30 42 47]
 [33 40 10  8 29 48 24  8]
 [14 49  8 46 23 18 10 49]
 [15 20 49 30  9 18 42  5]]



RESULT:
 [[ 2 30 42 47 12  0  1 40]
 [29 48 24  8 33 40 10  8]
 [23 18 10 49 14 49  8 46]
 [ 9 18 42  5 15 20 49 30]
 [28 27 31 35 49  5 49  1]
 [20  2 42 48 21 12 34  3]
 [28 31 47 34 21 22 39 23]
 [19 32 27 20 37  6 24 22]]


In [7]:
'''
Небольшие заметки. Не часть лабораторной. Будет убрано
'''

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print("vv:\n",vv)  
y = x + vv  # Add x and vv elementwise
print("vv:\n",y)

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
print("np.reshape(v, (3, 1)) * w:\n",np.reshape(v, (3, 1)) * w)
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print("x + v:\n",x + v)
print("x:\n",x)
print("w:\n",w)
print("x.T:\n",x.T)
print("(x.T + w):\n",(x.T + w))
print("(x.T + w).T:\n",(x.T + w).T)
print("np.reshape(w, (2, 1):\n",np.reshape(w, (2, 1)))

vv:
 [[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
vv:
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
np.reshape(v, (3, 1)) * w:
 [[ 4  5]
 [ 8 10]
 [12 15]]
x + v:
 [[2 4 6]
 [5 7 9]]
x:
 [[1 2 3]
 [4 5 6]]
w:
 [4 5]
x.T:
 [[1 4]
 [2 5]
 [3 6]]
(x.T + w):
 [[ 5  9]
 [ 6 10]
 [ 7 11]]
(x.T + w).T:
 [[ 5  6  7]
 [ 9 10 11]]
np.reshape(w, (2, 1):
 [[4]
 [5]]
