# Программирование Python

## "Обработка многомерных массивов в библиотеке NumPy с использованием IPython"

Выполнил студент Мурсалимов Акмаль Тимурович группы ИС/м-20-1-о.

In [1]:
import numpy as np
from tabulate import tabulate
import pandas as pd

##### <font color='red'>Задание</font>

Создать класс, реализующий функционал учета рейтинга студентов **StudentsRaiting**. Класс должен иметь конструктор, который будет принимать список студентов с результатами сданных экзаменов, реализованый в виде словаря с ключем "ФИО студента" и оценками по экзаменам по 4 предметам (Программирование, Дискретная математика, Иностранный язык, Философия), представленными в виде упорядоченного множества (кортежа). Например:

`{"Иванов Петр Николавич":(3,3,5,4), "Петров Иван Константинович":(5,4,5,4)}`

Релизовать методы: 
- добавления студента с оценками по экзаменам
- удаления студента из рейтинга 
- получения списка студентов с рейтингом выше порогового
- метод демонстрации работы методов класса с выводом результатов на печать в виде текстовой таблицы.

Примечание:
Рейтинг составляется по суммарному баллу по всем предметам.

In [2]:
class StudentsRaiting:    

    # Constructor
    def __init__(self, students):
        self.students = students  
 

    def printStudents(self, data = None):
        if data == None: 
            data = self.students
        df = pd.DataFrame({'Student' : list(data.keys()),
                       'Marks' : list(data.values())})
        print(tabulate(df, headers='keys', tablefmt='psql'))
   
    def show(self):
        print(self.students)
        
    def addStud(self,student):
        if type(student) is dict:
            self.students.update(student)
        
    def delStud(self,student):
        self.students.pop(student,None)
        
    def getStudsWithRating(self,rating):
        if type(rating) is not int: 
            return None
        result = {}
        for a,b in self.students.items():
            if sum(b)>=rating:
                result.update({a:b})
        self.printStudents(result)
        
       

print("Initializing new journal:")

journal = StudentsRaiting({"Иванов Петр Николавич":(3,3,5,4),
                     "Петров Иван Константинович":(5,4,5,4),
                     "Иванов Иван Константинович":(4,5,3,5),
                     "Петров Петр Николавич":(4,4,3,4)})  

journal.printStudents() 



print("\n\n\n")

print("Adding new students:")

journal.addStud({"Аааа ААА Аааааа":(5,5,5,5),
                 "BBB bbb BBBBbbbb":(2,3,2,2)})

journal.printStudents() 



print("\n\n\n")

print("Removing student by name:")

journal.delStud("Аааа ААА Аааааа")

journal.printStudents() 


print("\n\n\n")

print("Getting students with good rating (more than 15):")

journal.getStudsWithRating(15)








Initializing new journal:
+----+----------------------------+--------------+
|    | Student                    | Marks        |
|----+----------------------------+--------------|
|  0 | Иванов Петр Николавич      | (3, 3, 5, 4) |
|  1 | Петров Иван Константинович | (5, 4, 5, 4) |
|  2 | Иванов Иван Константинович | (4, 5, 3, 5) |
|  3 | Петров Петр Николавич      | (4, 4, 3, 4) |
+----+----------------------------+--------------+




Adding new students:
+----+----------------------------+--------------+
|    | Student                    | Marks        |
|----+----------------------------+--------------|
|  0 | Иванов Петр Николавич      | (3, 3, 5, 4) |
|  1 | Петров Иван Константинович | (5, 4, 5, 4) |
|  2 | Иванов Иван Константинович | (4, 5, 3, 5) |
|  3 | Петров Петр Николавич      | (4, 4, 3, 4) |
|  4 | Аааа ААА Аааааа            | (5, 5, 5, 5) |
|  5 | BBB bbb BBBBbbbb           | (2, 3, 2, 2) |
+----+----------------------------+--------------+




Removing student by name:
+

##### <font color=red>Задание</font>
Создать массив значений типа `int32` размером 10х10, состоящий из равномерно распределенных случайных чисел от 0 до 100. Получить 4 копии этого массива со значениями типа `uint32`,`int64`,`uint64`,`float`. Для каждого массива вывести сведения: число размерностей, форма, размер, тип данных, размер каждого значения в байтах и размер всего массива в байтах.


In [3]:
massives = ([np.random.randint(100, size=(10, 10))])

massives.extend([np.array(massives[0], dtype=np.uint32),
             np.array(massives[0], dtype=np.int64),
             np.array(massives[0], dtype=np.uint64),
             np.array(massives[0], dtype=np.float)])

df = pd.DataFrame({'Name' : ["Main","Copy №1","Copy №2","Copy №3","Copy №4",],
                   'Type' : list(map(lambda s: s.dtype, massives)),
                   'Dimensions' : list(map(lambda s: s.ndim, massives)),
                   'Shape' : list(map(lambda s: s.shape, massives)),
                   'Size' : list(map(lambda s: s.size, massives)),
                   'ItemWeight(Bytes)' : list(map(lambda s: s.itemsize, massives)),
                   'Weight(Bytes)' : list(map(lambda s: s.nbytes, massives))})
print(tabulate(df, headers='keys', tablefmt='psql'))

+----+---------+---------+--------------+----------+--------+---------------------+-----------------+
|    | Name    | Type    |   Dimensions | Shape    |   Size |   ItemWeight(Bytes) |   Weight(Bytes) |
|----+---------+---------+--------------+----------+--------+---------------------+-----------------|
|  0 | Main    | int32   |            2 | (10, 10) |    100 |                   4 |             400 |
|  1 | Copy №1 | uint32  |            2 | (10, 10) |    100 |                   4 |             400 |
|  2 | Copy №2 | int64   |            2 | (10, 10) |    100 |                   8 |             800 |
|  3 | Copy №3 | uint64  |            2 | (10, 10) |    100 |                   8 |             800 |
|  4 | Copy №4 | float64 |            2 | (10, 10) |    100 |                   8 |             800 |
+----+---------+---------+--------------+----------+--------+---------------------+-----------------+


##### <font color=red>Задание</font>
Выполнить следующий код и объяснить результат.

In [4]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("A mass:", a)
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print("col_r1, col_r1.shape: \n", col_r1, col_r1.shape)
print()
print("col_r2, col_r2.shape: \n",col_r2, col_r2.shape)

A mass: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
col_r1, col_r1.shape: 
 [ 2  6 10] (3,)

col_r2, col_r2.shape: 
 [[ 2]
 [ 6]
 [10]] (3, 1)


##### <font color=green>Ответ</font>
col_r1 = a[:, 1] - берем второй элемент из всех строк исходного массива. ":" - выбрать все элементы данного измерения массива

col_r2 = a[:, 1:2] - берем С первого ПО второй элемент из всех строк исходного массива.

Функция Shape позволяет узнать форму массива.

##### <font color=red>Задание</font>
Создать массив случайных целочисленных значений (от -100 до 100) размером 8x8. Используя индексацию булевыми массивами получить:
1. Все элементы, значения которых являются четными числами. Вывести их маску в массиве.
2. Все элементы, значения которых попадают в диапазон от 10 до 50. Вывести их маску в массиве.
3. Все элементы, значения которых являются четными числами и попадают в диапазон от 10 до 50. Вывести их маску в массиве.
4. Все элементы, значения которых являются нечетными числами и модуль значения которых из диапазона от 10 до 50. Вывести их маску в массиве.
5. Все элементы, значения которых являются нечетными числами или отрицательными.

In [5]:


main_mass = np.random.randint(-100, 100, size=(8, 8))
print('main_mass\n',main_mass)

print("\n\n\nTask №1:\nВсе элементы, значения которых являются четными числами:\n",
      main_mass[main_mass%2==0])
print("\n\nМаска:\n",(main_mass%2==0))


print("\n\n\nTask №2:\nВсе элементы, значения которых попадают в диапазон от 10 до 50:\n",
      main_mass[(main_mass >=10 )&(main_mass <=50 )])
print("\n\nМаска:\n",((main_mass >=10 )&(main_mass <=50 )))

print("\n\n\nTask №3:\nВсе элементы, значения которых являются четными числами и попадают в диапазон от 10 до 50:\n",
      main_mass[(main_mass%2==0)&(main_mass >=10 )&(main_mass <=50 )])
print("\n\nМаска:\n",((main_mass%2==0)&(main_mass >=10 )&(main_mass <=50 )))

print("\n\n\nTask №4:\nВсе элементы, значения которых являются нечетными числами",
      " и модуль значения которых из диапазона от 10 до 50:\n",
      main_mass[(main_mass%2!=0)&(abs(main_mass) >=10 )&(abs(main_mass) <=50 )])
print("\n\nМаска:\n",((main_mass%2!=0)&(abs(main_mass) >=10 )&(abs(main_mass) <=50 )))


print("\n\n\nTask №5:\nВсе элементы, значения которых являются нечетными числами или отрицательными:\n",
      main_mass[(main_mass%2!=0)|(main_mass <0 )])
print("\n\nМаска:\n",((main_mass%2!=0)|(main_mass <0 )))

main_mass
 [[-86  95 -64 -75   3  42 -35 -94]
 [ 30  13 -57 -46  26 -14  85  52]
 [ 40 -75 -39 -66  33  78 -96  33]
 [-77  14  93  93 -77  45  97  55]
 [ 70  30 -94  51 -58  85  84  57]
 [-14  62 -11  95  64 -52  86  16]
 [ 73  58  16  88 -86 -56 -31  29]
 [ 17   8  53  85 -39  -2 -27 -49]]



Task №1:
Все элементы, значения которых являются четными числами:
 [-86 -64  42 -94  30 -46  26 -14  52  40 -66  78 -96  14  70  30 -94 -58
  84 -14  62  64 -52  86  16  58  16  88 -86 -56   8  -2]


Маска:
 [[ True False  True False False  True False  True]
 [ True False False  True  True  True False  True]
 [ True False False  True False  True  True False]
 [False  True False False False False False False]
 [ True  True  True False  True False  True False]
 [ True  True False False  True  True  True  True]
 [False  True  True  True  True  True False False]
 [False  True False False False  True False False]]



Task №2:
Все элементы, значения которых попадают в диапазон от 10 до 50:
 [42 30 13 2

##### <font color=red>Задание</font>
Написать функцию, которая из исходного массива размером 8х8 получает (при помощи операций разбиения и объединения) массив, в котором переставлены квадранты 1-й с 3-м, 2-й с 4-м по сравнению с исходным массивом. Продемонстрировать работу функции все шаги алгоритма сопроводить подробными комментариями и отладочным выводом промежуточных результатов.

Т.е. например из массива

`[[49  5 49  1 28 27 31 35]
 [21 12 34  3 20  2 42 48]
 [21 22 39 23 28 31 47 34]
 [37  6 24 22 19 32 27 20]
 [12  0  1 40  2 30 42 47]
 [33 40 10  8 29 48 24  8]
 [14 49  8 46 23 18 10 49]
 [15 20 49 30  9 18 42  5]]`
 
должен получиться массив 

 `[[ 2 30 42 47 12  0  1 40]
 [29 48 24  8 33 40 10  8]
 [23 18 10 49 14 49  8 46]
 [ 9 18 42  5 15 20 49 30]
 [28 27 31 35 49  5 49  1]
 [20  2 42 48 21 12 34  3]
 [28 31 47 34 21 22 39 23]
 [19 32 27 20 37  6 24 22]]`

In [6]:
def replace_squares(mass,mid=False):
    if list(mass.shape)[0]%2!=0 or list(mass.shape)[1]%2!=0:
        return None    
    sh = [list(mass.shape)[0]//2,list(mass.shape)[1]//2]    
    res = mass.copy()
    squares = (mass[:sh[0],:sh[1]],
              mass[sh[0]:,:sh[1]],
              mass[:sh[0],sh[1]:],
              mass[sh[0]:,sh[1]:])
    if mid:
        middle_results = list(squares)
        print("\n\nMiddle results:\n\nFirst square: \n",middle_results[0],
              "\nSecond square: \n",middle_results[1],
              "\nThird square: \n",middle_results[2],
              "\nFourth square: \n",middle_results[3])
    res[sh[0]:,sh[1]:],res[:sh[0],sh[1]:],res[sh[0]:,:sh[1]],res[:sh[0],:sh[1]]=squares
    return res
    
    
#massive = np.random.randint(-5, 5, size=(8,8))
massive = np.array([[49,  5, 49,  1, 28, 27, 31, 35],
                    [21, 12, 34,  3, 20,  2, 42, 48],
                    [21, 22, 39, 23, 28, 31, 47, 34],
                    [37,  6, 24, 22, 19, 32, 27, 20],
                    [12,  0,  1, 40,  2, 30, 42, 47],
                    [33, 40, 10,  8, 29, 48, 24,  8],
                    [14, 49,  8, 46, 23, 18, 10, 49],
                    [15, 20, 49, 30,  9, 18, 42,  5]])
print("Input massive:\n", massive)
#if middle results are in need, add True
#massive = replace_squares(massive,True)
massive = replace_squares(massive)
print("\n\n\nRESULT:\n",massive)

Input massive:
 [[49  5 49  1 28 27 31 35]
 [21 12 34  3 20  2 42 48]
 [21 22 39 23 28 31 47 34]
 [37  6 24 22 19 32 27 20]
 [12  0  1 40  2 30 42 47]
 [33 40 10  8 29 48 24  8]
 [14 49  8 46 23 18 10 49]
 [15 20 49 30  9 18 42  5]]



RESULT:
 [[ 2 30 42 47 12  0  1 40]
 [29 48 24  8 33 40 10  8]
 [23 18 10 49 14 49  8 46]
 [ 9 18 42  5 15 20 49 30]
 [28 27 31 35 49  5 49  1]
 [20  2 42 48 21 12 34  3]
 [28 31 47 34 21 22 39 23]
 [19 32 27 20 37  6 24 22]]


In [7]:
def translation_check(A,B):
    try:
        RESULT=A+B
    except:
        print(A.shape," + ",B.shape," Выбрасывает исключение")
    else:
        print(A.shape," + ",B.shape," = RESULT.shape",RESULT.shape)
        
print("Проверка практичным методом: ")
translation_check(np.ones((100,100,4)), np.ones(3))
translation_check(np.ones((15,1,6,5)), np.ones((7,1,5)))
translation_check(np.ones((12,3,8)), np.ones((3,1)))
translation_check(np.ones((10,4,1,6)), np.ones((3,1,6)))
translation_check(np.ones((10,1)), np.ones((1,10,3)))
print("Результаты, которые не выбросили исключение, при не совпадении размерности дополнялись единицами слева.\n",
      "Затем все единицы приводились к соответствующей размерности в суммируемых массивах.\n",
      "Исключения были выброшены в тех случаях, когда размерности измерений не совпадали и не являлись единицами.")

Проверка практичным методом: 
(100, 100, 4)  +  (3,)  Выбрасывает исключение
(15, 1, 6, 5)  +  (7, 1, 5)  = RESULT.shape (15, 7, 6, 5)
(12, 3, 8)  +  (3, 1)  = RESULT.shape (12, 3, 8)
(10, 4, 1, 6)  +  (3, 1, 6)  Выбрасывает исключение
(10, 1)  +  (1, 10, 3)  = RESULT.shape (1, 10, 3)
Результаты, которые не выбросили исключение, при не совпадении размерности дополнялись единицами слева.
 Затем все единицы приводились к соответствующей размерности в суммируемых массивах.
 Исключения были выброшены в тех случаях, когда размерности измерений не совпадали и не являлись единицами.


##### <font color=red>Задание</font>
Создать класс наследник от класса учета рейтинга студентов (**StudentsRaiting**) и расширить его методами рассчета статистики по предметам (средний балл, максимальный балл, минимальный балл). Для этого нужно преобразовать данные об оценках из словаря в массив и использовать функции библиотеки Numpy.
(Программирование, Дискретная математика, Иностранный язык, Философия)

Примечание: Использовать универсальные функции для работы с массивами numpy.

In [8]:
class StudentsRaitingExtanded(StudentsRaiting):
    
    def __init__(self, students):
        StudentsRaiting.__init__(self,students)
        
    def __printSubjectStatistics__(self,name,subjects,marks,counts):
        df = pd.DataFrame({name : subjects,
                       'Балл' : marks,
                       'Количество' : counts})
        print(tabulate(df, headers='keys', tablefmt='psql'))
        
    def showStatistics(self):
        subjNames=["Программирование", "Дискретная математика", "Иностранный язык", "Философия"]
        marks = ["Минимальный балл: ","Средний балл: ","Максимальный балл: "]
        source = np.array(list(self.students.values()),dtype=np.float)
        statistics = np.array([np.amin(source,0),np.round(np.average(source,0)),np.amax(source,0)])
        print("Статистика по предметам:")
        for i in range(4):
            self.__printSubjectStatistics__(subjNames[i],marks,statistics[0:3,i],
                                       list(map(lambda s: list(source[:,i]).count(s), statistics[0:3,i])))
        
journalExtanded = StudentsRaitingExtanded({"Иванов Петр Николавич":(3,3,5,4),
                                           "Петров Иван Константинович":(5,4,5,4),
                                           "Иванов Иван Константинович":(4,5,3,5),
                                           "Петров Петр Николавич":(4,4,3,4)})  
journalExtanded.printStudents()
print('\n\n')
journalExtanded.showStatistics()

+----+----------------------------+--------------+
|    | Student                    | Marks        |
|----+----------------------------+--------------|
|  0 | Иванов Петр Николавич      | (3, 3, 5, 4) |
|  1 | Петров Иван Константинович | (5, 4, 5, 4) |
|  2 | Иванов Иван Константинович | (4, 5, 3, 5) |
|  3 | Петров Петр Николавич      | (4, 4, 3, 4) |
+----+----------------------------+--------------+



Статистика по предметам:
+----+--------------------+--------+--------------+
|    | Программирование   |   Балл |   Количество |
|----+--------------------+--------+--------------|
|  0 | Минимальный балл:  |      3 |            1 |
|  1 | Средний балл:      |      4 |            2 |
|  2 | Максимальный балл: |      5 |            1 |
+----+--------------------+--------+--------------+
+----+-------------------------+--------+--------------+
|    | Дискретная математика   |   Балл |   Количество |
|----+-------------------------+--------+--------------|
|  0 | Минимальный балл:     

##### <font color=red>Задание</font>
0. Создать функцию `Function1(x)`, возвращающую вектор `y`, размер которого равен размеру вектора `x` и выполняющую поэлементное вычисление по формуле `y=1/(1+exp(-x)`. Создать функцию `Function2(x)`, возвращающую вектор `y`, размер которого равен размеру вектора `x` и выполняющую поэлементное вычисление по формуле `y=max(0,x)`.
1. Написать функцию `LinearTransform(M,x,b)`, где `M` - матрица, `x` - вектор, `b` - число. Функция должна ввозвращать вектор `y`, размер которого равен размеру вектора `x`, где `y` рассчитывается по формуле `y=M*x+b`, здесь под операцией `*` понимается операция скалярного произведения (dot product) матрицы на вектор.
2. Написать функцию `Transform(M1,M2,x,b1,b2)`, где `M1`,`M2` - матрицы, `x` - вектор, `b1`,`b2` - числа. Функция должна ввозвращать вектор `y`, размер которого равен размеру вектора `x`, где `y` рассчитывается по формуле `y=Function2(LinearTransform(M2,x2,b2))`, а `x2=Function1(LinearTransform(M1,x,b1))`.
3. Задать матрицы M1,M2 размером MxN, вектор размером N, и числа b1,b2 и выполнить вычисления `Transform(M1,M2,x,b1,b2)`, производя замеры времени выполнения функции. **Значения M и N нужно узнать у преподавателя.** 

Все функции задания нужно реализовать в двух вариантах: 
* с использованием универсальных векторизованных операций;
* с использованием циклов для вычислений.

Сравнить время выполнения для обеих реализаций и сделать выводы.

In [ ]:
#Ага, здесь реализация, да

#### <font color=red>Задание</font>
Построить графики функций: $y=\sin(x)$,$y=\cos(x)$, $y=tg(x)$, $y=ctg(x)$. 
Требования к графикам:
- все графики в одной системе координат
- значения по оси x должны меняться от $-\pi$ до $\pi$.
- подписи по осям координат 
- название графика
- координатная сетка
- легенда.

In [ ]:
#Ага, здесь реализация, да

#### <font color=red>Задание</font>
Построить графики функций: $y=2\cdot x^2$, $y=-2\cdot x^2$, $x=2\cdot y^2$, $x=-2\cdot y^2$
Требования к графикам:
- каждый график построить в своей системе координат, разделив лист на 4 равные части 2х2.
- значения по осям x и y должны меняться от 5 до 5.
- подписи по осям координат 
- названия графиков
- координатная сетка.

In [ ]:
#Ага, здесь реализация, да

#### <font color=red>Задание</font>
Сгенерировать 1000 случайных значений выбранного распределения (вид уточнить у преподавателя) и построить гистограмму частот и гистограмму относительных частот. 
Требования к графикам:
- графики расположить горизонтально
- подписи по осям координат 
- названия графиков.

In [ ]:
#Ага, здесь реализация, да

#### <font color=red>Задание</font>
Повторить крайний пример, изменив вид распределений, используемый для генерации массивов x и y (вид распределений уточнить у преподавателя).

In [ ]:
#Ага, здесь реализация, да

#### <font color=red>Задание</font>
1. Выбрать произвольное цветное изображение и загрузить в среду IPython.
2. Построить гистограммы яркостей для всех трех каналов.
3. Используя матричные операции обнулить яркости синего и зеленого каналов в изображении и отобразить его. 
4. Используя матричные операции обнулить яркости красного канала в изображении и отобразить его.

In [ ]:
#Ага, здесь реализация, да